/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_systemprj;

/**
 *
 * @author User
 */
public class RegisterWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterWindow.class.getName());

    /**
     * Creates new form Login
     */
    public RegisterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerBTN = new javax.swing.JButton();
        LoginBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        FullNameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PhoneNumberTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UserNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JTextField();
        registerBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Your Luxury Experience Awaits");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 100, 180, 20);

        jLabel2.setText("Grand Hotel");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 40, 130, 50);

        registerBTN.setText("Register");
        jPanel1.add(registerBTN);
        registerBTN.setBounds(20, 560, 310, 40);

        LoginBTN.setText("Login");
        jPanel1.add(LoginBTN);
        LoginBTN.setBounds(200, 140, 130, 30);

        jLabel4.setText("jLabel3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 60, 16);

        FullNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(FullNameTF);
        FullNameTF.setBounds(20, 220, 310, 40);

        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 270, 60, 16);

        EmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTFActionPerformed(evt);
            }
        });
        jPanel1.add(EmailTF);
        EmailTF.setBounds(20, 290, 310, 40);

        jLabel6.setText("jLabel3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 60, 16);
        jPanel1.add(PhoneNumberTF);
        PhoneNumberTF.setBounds(20, 360, 310, 40);

        jLabel7.setText("jLabel3");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 410, 60, 16);
        jPanel1.add(UserNameTF);
        UserNameTF.setBounds(20, 430, 310, 40);

        jLabel8.setText("jLabel3");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 480, 60, 16);
        jPanel1.add(PasswordTF);
        PasswordTF.setBounds(20, 500, 310, 40);

        registerBTN1.setText("Register");
        jPanel1.add(registerBTN1);
        registerBTN1.setBounds(20, 140, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void FullNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FullNameTF;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JTextField PasswordTF;
    private javax.swing.JTextField PhoneNumberTF;
    private javax.swing.JTextField UserNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerBTN;
    private javax.swing.JButton registerBTN1;
    // End of variables declaration//GEN-END:variables
}
